### ISSUE TITLE
AdobeBlank comment

### ISSUE THREAD

**Issue by polarathene** [Pomax/CFF-glyphlet-fonts#12]
Hi there, I saw your comment from an [announcement of the original Adobe Blank font](https://blogs.adobe.com/typblography/2013/03/introducing-adobe-blank.html) from years ago. You mentioned:

> It might be possible to create a minimal full-unicode font by using format 4 and 12 CMAP entries with full-range segments, both pointing to the non-spacing, non-marking glyph. This would probably give us a legal OpenType font that’s around 1kb. I’ll see if I can play around with that over the weekend. If I can, I’ll put it on github.

Did anything ever come of that? Is that this or one of the other repos here?

**Comment by Pomax** [comment]
We invented a new CMAP subformat for that, so rather than using 4+12, you can now implement [format 13](https://docs.microsoft.com/en-us/typography/opentype/spec/cmap#format-13-many-to-one-range-mappings) with a ConstantMapGroup that starts at 0x00000001 (because 0 is reserved) and ends at 0xFFFFFFFF and you're done.

**Comment by behdad** [comment]
The following does the format 13 trick:
https://github.com/santhoshtr/tofudetector
