### ISSUE TITLE
How to use your JS tool to create custom ligatures

### ISSUE THREAD

**Issue by simevidas** [Pomax/CFF-glyphlet-fonts#6]
Could you explain how to use your tool to generate custom OpenType data URIs? E.g. I would like to replace the word "foo" with a custom SVG path.

I'm looking at your article and the process of generating the OpenType data URI is placed in the uglified generator.js file, so I'm having trouble figuring out how this works.

Maybe it would make sense to provide an API which would enable generating the data URI, e.g.

``` js
var dataURI = generate({
    "custom": "M 20 -20 L 20 680 700 680 700 -20 20 -20 M 170 130 L 550 130 550 530 170 530",
    "foo": "…",
    "bar": "…"
});
```

**Comment by Pomax** [comment]
the one used on the page is uglified, the repo you posted this question in has all the normal human readable code right here =)

All the normal source is found in https://github.com/Pomax/CFF-glyphlet-fonts/tree/gh-pages/src but the trick here is that every struct serializes itself to byte code, so it's simply a `font.toData()`, which generates a large byte string, which is then run through the browser's `btoa`, which converts a binary blob into a base64 string. At that point the trick is the same as for any data-uri: say which mime-type it is, add the word base64, append the base64 string. Done

Have a look at https://github.com/Pomax/CFF-glyphlet-fonts/blob/gh-pages/src/utils/buildTables.js#L84 for instance, which forms the download links from the font.

It might seem convenient to add that function to the font, but need context knowledge: you'd still need to push the mime-type into the function in order to generate the correct url, which makes calling the function pretty much just as much work as just creating the data-url string with `"data:mime/type;base64," + btoa(data)`

**Comment by simevidas** [comment]
Thanks for the instructions :)
