### ISSUE TITLE
Adding the ligature to the original webfont?

### ISSUE THREAD

**Issue by simevidas** [Pomax/CFF-glyphlet-fonts#7]
I'm having a [discussion on Twitter](https://twitter.com/pixelambacht/status/489413515468611584) about your method of replacing custom words with OpenType ligatures. Would it be possible to add the ligature to the original font so that we don't have to wrap the custom word in a dedicated element like `<span class="custom">`?

**Comment by RoelN** [comment]
If you create a .ttx of the font with [ttx/fonttools](https://github.com/behdad/fonttools/), you can do this. You'd have to put the ligature glyph in the font (adding it to the glyphorder, glyf, cmap and htmx tables). Then you can copy over the gsub-table (or append your custom ligature to the existing one) and convert the font back to TTF, you'll have the original font with your custom ligature.

A post on this is coming very soon on http://pixelambacht.nl :)

**Comment by Pomax** [comment]
The only reason it's wrapped by a "custom" classed `<span>` in my article is that my font does not contain any other letters, so if I were to set it as the main body font (say css `font-family: custom, serif;`), it'd be a guaranteed 99.99999% miss rate on any letter it needs to style, falling back to the next font in the CSS list. This would be silly =P

However, if you have a fully specified font with enough glyphs to style text _and_ you have the ligatures in it: perfect! If you have a font, and you have ligatures for that font, add them all in the same font.

(symbolset, for instance, supports ascii so that it can be used as a "main font" while also applying its symbols through ligature substitution when it needs to)

**Comment by simevidas** [comment]
Doing `font-family: custom, serif` on your font is not possible, since any appearance of the individual letters (c, u, s, t, etc.) in other word combinations is removed, i.e. the letters are hidden. Demo: http://jsfiddle.net/simevidas/MxqkL/

If your font could only replace the word "custom" with the ligature and ignore any other appearances of those letters, i.e. have the next font in the font stack render them, that would be great I think. Such a pattern is demonstrated here: https://codepen.io/SitePoint/pen/viBGh

![subset](https://cloud.githubusercontent.com/assets/716405/3602688/0c530be8-0d0f-11e4-86c3-757a9eee6ef4.png)

But if that's not possible, merging the ligatures with a base font seems to be the way to go.

**Comment by Pomax** [comment]
That should actually be entirely possible, by first trying to resolve "custom" in the GSUB table, followed by resolving the individual letters `c -> .notdef`, `u -> .notdef`, etc. That's actually a great point, and I'll try to see if I can ammend the generator and article to mention and make use of that.

**Comment by simevidas** [comment]
Good to hear :)

**Comment by RoelN** [comment]
I created a test font in Icomoon, mapping an icon to the word "aapje" and another icon to the word "frits". When using @Heydon's technique I get the problem @simevidas describes: all the individual letters in those two words will show up empty. For instance, "whaap" will show up as "wh&nbsp;&nbsp;&nbsp;".

So I tried @Pomax's suggestion, adding a `.notdef` glyph and mapping the individual letters to them in the `cmap` table, turning

`<map code="0x61" name="a"/><!-- LATIN SMALL LETTER A -->`

into

`<map code="0x61" name=".notdef"/><!-- LATIN SMALL LETTER A -->`

But now not only the individual letters don't shop up, the ligature is also broken. A simple test page [can be found here](http://pixelambacht.nl/demo/notdef/testpage-notdef.html). A direct link to the .ttx [is here](http://pixelambacht.nl/demo/notdef/notdef-test/icomoon-met.ttx). It's kinda my own mess-around test stuff, so apologies for the weird naming schemes and stuff. But apart from that, I think this .ttx is proper and should work, but it doesn't. Any ideas?

(The text on that page is contenteditable, ligatures are mapped to "aapje" and "frits")

**Comment by jfkthame** [comment]
I don't see how this could be expected to work. Mapping the individual letters to .notdef in the cmap can't work, because then you can't match them in the GSUB rule for the ligature. They need individual GlyphIDs for that, and the cmap has to generate those GIDs.

(What @Pomax meant, AIUI, was to map the individual-letter GIDs to .notdef in a GSUB lookup, _after_ the lookup that forms the ligature, so that if they didn't get ligated then they'll disappear.)

But I still don't think that can work. As soon as the cmap includes entries mapping the characters to GIDs (other than .notdef), most software is going to understand that as meaning that the characters are supported by the font, and so it won't try to fall back to some other font.

If the GSUB then maps those individual glyphs to .notdef, I'd expect .notdef to be rendered (visibly or not, depending whether it's a visible glyph in the font); I would _not_ expect applications to look at the post-GSUB result and then decide to go back and use a different font. The font-selection decision is normally based only on cmap coverage, AFAIK.

**Comment by twardoch** [comment]
To solve this properly, you need to remember the character vs. glyph distinction. 
1. If you don't care about maintaining the correct character backing string, e.g. the Unicode string "desktop" in your content, then it doesn't really matter how you solve this, and using OpenType Layout features doesn't seem to make much sense. It's better the produce just one glyph with your "ligature" and encode it directly in the cmap, e.g. using a PUA codepoint. 
2. If maintaining the character backing string does matter for you, then you need to realize that the cmap -> GID mapping works so that you need to have a glyph for each cmap codepoint. Of course if you want to make a font that ONLY has the ligature representing "desktop", then you can have one outlineless zero-width glyph with whatever glyphname (e.g. /myglyph) to which all cmap entries map: 

```
# cmap
U+0064 (d): /myglyph
U+0065 (e): /myglyph
U+0073 (s): /myglyph
U+006B (k): /myglyph
U+0074 (t): /myglyph
U+006F (o): /myglyph
U+0070 (p): /myglyph
```

Then, you'd have another glyph, your ligature glyph, (with whatever name, e.g. /d_e_s_k_t_o_p if you want to be Adobe-compatible), and you'd have one GSUB substitution: 

```
# GSUB
lookup liga { 
  sub myglyph myglyph myglyph myglyph myglyph myglyph myglyph by d_e_s_k_t_o_p;
} liga; 
feature liga { 
  lookup liga; 
} liga; 
```

This way, given the "liga" feature is processed, the Unicode string "desktop" will produce the ligature glyph /d_e_s_k_t_o_p, but also, in this setup, the Unicode strings "dekstop", "edsktop" "sdeoptk" etc. will produce the same ligature. This MAY be what you want :) 

If you want to be more specific and have the ligature appear ONLY if the string "desktop" appears, then indeed, you need to make stub glyphs (outlineless, zero-width) for each Unicode character: 

```
# cmap
U+0064 (d): /d
U+0065 (e): /e
U+0073 (s): /s
U+006B (k): /k
U+0074 (t): /t
U+006F (o): /o
U+0070 (p): /p
```

```
# GSUB
lookup liga { 
  sub d e s k t o p by d_e_s_k_t_o_p;
} liga; 
feature liga { 
  lookup liga; 
} liga; 
```

If you want, for example, to make sure that the strings "desktop", "Desktop", "DESKTOP" etc. produce your ligature, then you'd make your cmap: 

```
# cmap
U+0044 (D): /d
U+0064 (d): /d
U+0045 (E): /e
U+0065 (e): /e
U+0053 (S): /s
U+0073 (s): /s
U+004B (K): /k
U+006B (k): /k
U+0054 (T): /t
U+0074 (t): /t
U+004F (O): /o
U+006F (o): /o
U+0050 (P): /p
U+0070 (p): /p
```

and the GSUB feature the same way as in the previous example. 

You're free to control at which point you want to keep vs. lose the uniqueness/distinction, but always remember that the layout process consists of at the very least two steps: 
1. Unicode character to default glyph mapping (cmap to GID). 
2. Glyph processing using OpenType Layout tables (GSUB, GPOS), which only work on the level of GIDs. 

There is really no "best" way to do this. There are multiple ways, depending on what side conditions you want your font to fulfill. But, in SFNT and OpenType Layout, there is no single-step solution that would allow you to perform a conversion from a string of Unicode characters to one glyph. 

Best,
Adam

**Comment by Pomax** [comment]
@RoelN as @twardoch highlights, you need valid cmap entries for any letter that has to "do" something in a font, so we can't (effectively) blank the CMAP table. @jfkthame's point that most engines will not backtrack on their conclusion that a character is support may be true, but that doesn't rule out that the spec might say an engine may conclude a character is not supported after GSUB has taken place. If the spec allows it, then this could be an interesting "in-the-past-edge-case-but-not-anymore" that might be worth reexamining, given how established the use of OpenType fonts on the web now is, and the plethora of high quality icon fonts that have been getting released in the last two years. Time for some spec diving!

**Comment by behdad** [comment]
Every engine assumes that any combination of chars that are mapped in cmap are supported.  You can't backtrack from that.  It's too late.

**Comment by Pomax** [comment]
Rereading the CMAP section we have "Character codes that do not correspond to any glyph in the font should be mapped to glyph index 0"[¹](http://www.microsoft.com/typography/otspec/cmap.htm), so that would appear to be the crux: in order to use letters for ligatures we must have them exist in the cmap or we cannot reference them, and if they are in the cmap, they must necessarily implement some glyph, even if that glyph is empty.

we could squint and say that .notdef is also a glyph, and therefore GSUB rules for `a -> .notdef` should work, but from what I can tell after rereading the spec this would lead to the hilarious situation where the font says it supposed a character, and its outline is the same as the .notdef outline. Instead of falling through to the next font due to an unsupported character, we would see something like `??????` while typing `deskto`, and then an actual icon once we add the final `p` to form `desktop`.

But, there's also nothing in the spec that says what engines should do if a substitution yields a replacement to .notdef so while I have low hopes that the world will be willing to go "oh hey that's a really creative attempt at indicating an unsupported [character/sequence], let's formalise this as an explicitly valid possible effect of GSUB processing", it's certainly worth asking the OpenType community what they think about it.

That said, in the mean time I guess we're stuck with "it would be really cool if this were possible but it's kind of not".

@simevidas Your example works because the font you're requesting only contains `&`, which is different from ligatures: if it contained `&` as a ligature for `etc.` then it would also support `e`, `t`, `c`, and `.` and an `<h1>Rock etc. Roll is certainly cool</h1>` would be a mix of Lobster Two and Bevan in the words `certainly` and `cool`.

**Comment by simevidas** [comment]
@Pomax Ok, so having individual letters rendered by the fallback font is not possible after all, the next best solution is to merge the ligatures with the original font, right?

**Comment by Pomax** [comment]
pretty much, yes. TTX would be the easiest way to do that, although you need to be careful to make sure the quad sizes are the same, otherwise you're going to have to scale the glyph's vertices before you merge it in (you might end up with a HUGE ampersand for instance, if the ligature's font uses a 2000 font unit quad, and the main font uses a 1024 font unit quad =)

**Comment by jfkthame** [comment]
Doesn't this assume the ligature glyphs are going to be used in conjunction with a specific text font? If you're making a font for one specific purpose, maybe that's reasonable, but this is primarily about icon fonts, isn't it? For any sort of general-purpose icon font, it seems unlikely that the accompanying text font is pre-determined. And people may well want to use the icons in conjunction with non-free text fonts that they're not permitted to modify.

IMO, a ligature-icons font should include some kind of legible glyphs for the basic ASCII characters just for usability reasons, but they should be kept as simple as possible, and the normal assumption should be that the icon font is explicitly applied to text runs that are meant to be rendered as icons, and not applied to surrounding text.

The exception would be when the ligatures really are somehow intrinsic to the text font design - e.g. a complex cursive font with certain words rendered as ornate ligatures. But for general icons, dingbats, etc., people should be expected to style their elements appropriately.

**Comment by Pomax** [comment]
You're not going to use your icon font in all text everywhere, but only in small fragments where you want some real text + icon, so it's up to you to decide how best to do that. You can have an icon font that also offers a reasonable looking implementation of the Latin unicode blocks, and then you could do without `<span>` elements, or you can keep things cleanly seperated and use a `<span>` or even custom element `<span-icon>` (using something like [polymer](http://www.polymer-project.org/)) to explicitly mark up those parts of text that are going to --in regular browsers-- show up as an icon (while staying a plain word for things like screen readers).

As a "what would you actually do, rather than what are possible options?" call, I don't think I'd advocate merging fonts, since I like to stick with CSS for styling, but markup for markup: that icon font isn't used "for text", it's used for showing the user a semantic icon (hopefully. Please never use the nonsense hamburger icon =D) so I think using markup to state which stretch of text has which semantic role is better than to make one font perform two roles opaquely. It also makes it way easier to just swap fonts and icon fonts in and out. Just change the `font-family` for your `.icon` class, and it won't affect your real text font, and vice versa.

**Comment by RoelN** [comment]
Ah, I really was on the wrong track there, that's not going to work. Thanks everybody for your insights!
